### ISSUE TITLE
Possible error in docs

### ISSUE THREAD

**Issue by GregPK** [krakphp/job#32]
When I set up my app with the config from the readme:

```
$kernel->config([
    'name' => 'jobs',
    'sleep' => 10, 
    ...
]);
```

I got: `Notice: Undefined index: queue in ../vendor/krak/job/src/Kernel.php`

After some code diving changed it to:

```
$kernel->config([
    'queue' => 'jobs',
    'sleep' => 10, 
    ...
]);
```

And it worked, so probably worth updating the docs. I can do it, just checking if this is indeed and an error in docs.

**Comment by ragboyjr** [comment]
Good catch man!

So, yes it is an error.

The name config key is only used for scheduler instances. Every queue instance must have the queue key set.

so in the following config:

```
[
  'name' => 'Acme Scheduler',
  'schedulers' => [
    ['queue' => 'jobs1'],
    ['queue' => 'jobs2']
  ]
]
```

The name field is only used if you want to have a scheduler manage several queues. The Acme Scheduler will be the main process that will start and will launch and manage two separate processes that will then manage each of those queues respectively.

By all means @GregPK, if you see an error, submit a PR, and I'll happily review :).

**Comment by ragboyjr** [comment]
Also if it helps, check the test/functional/kernel.php for an example of possible kernel configuration.
